# Neon PostgreSQL (Learner Lab no permite crear RDS)
DB_ENDPOINT=ep-still-wave-a4g886xd-pooler.us-east-1.aws.neon.tech
DB_PORT=5432
DB_NAME=neondb
DB_USERNAME=neondb_owner
DB_PASSWORD=tu_password_aqui
