# PLANTILLA - No commitear con valores reales
# Crear el secreto en el cluster:
# kubectl create secret generic backend-env -n despacho \
#   --from-literal=DB_ENDPOINT=TU-RDS.amazonaws.com \
#   --from-literal=DB_PORT=3306 \
#   --from-literal=DB_NAME=despacho_db \
#   --from-literal=DB_USERNAME=admin \
#   --from-literal=DB_PASSWORD=TU_PASSWORD

apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: despacho
type: Opaque
stringData:
  DB_ENDPOINT: REEMPLAZAR
  DB_PORT: "3306"
  DB_NAME: despacho_db
  DB_USERNAME: REEMPLAZAR
  DB_PASSWORD: REEMPLAZAR
